---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    interactive: yes
  tasks:
    - name: Initialize the game.
      include_tasks: init.yml

    - debug:
        msg: |
          Try your hand at governing Ancient Sumeria
          successfully for a 10 years term of office.

    - include_tasks: hamurabi-tasks.yml
