---
- hosts: all
  become: no
  gather_facts: no
  vars:
    interactive: no
  tasks:
    - include_tasks: ../../init.yml

    - name: Edict that the fair price of land should be no more than 20.
      set_fact:
        landrate: 20

    - name: Give the order to buy 0 acres of land.
      set_fact:
        action: { "user_input": 0 }
    - block:
        - include_tasks: ../../buy-acres.yml
      rescue:
        - name: This task should not be executed.
          fail:
            msg: "Buying 0 acre of land is a valid choice."
    - assert:
        that:
          - acres|int == 1000
          - bushels|int == 2800
          - population|int == 95

    - name: Give the order to buy 10 acres of land for 200 bushels.
      set_fact:
        action: { "user_input": 10 }
    - block:
        - include_tasks: ../../buy-acres.yml
      rescue:
        - name: This task should not be executed.
          fail:
            msg: "Buying 10 acre of land is a valid choice."
    - assert:
        that:
          - acres|int == 1010
          - bushels|int == 2600
          - population|int == 95

    - name: Give the order to buy 1000 acres of land for 20000 bushels.
      set_fact:
        action: { "user_input": 1000 }
    - block:
        - include_tasks: ../../buy-acres.yml
      rescue:
        - name: The game correctly detected there was not enough bushels.
          assert:
            that: action_failed.failed
    - assert:
        that:
          - acres|int == 1010
          - bushels|int == 2600
          - population|int == 95

    - name: Ok steward, calm down and let's buy 130 acres of land for 2600 bushels instead.
      set_fact:
        action: { "user_input": 130 }
    - block:
        - include_tasks: ../../buy-acres.yml
      rescue:
        - name: This task should not be executed.
          fail:
            msg: "Buying 130 acre of land is a valid choice."
    - assert:
        that:
          - acres|int == 1140
          - bushels|int == 0
          - population|int == 95
